# .github/workflows/generate_feed.yml
name: Generate Cropink XML Feed

on:
  schedule:
    # Runs the workflow every 3 hours (at minute 0 of every 3rd hour) in UTC.
    # This corresponds to 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00, 00:00 (next day) Estonia Time (EEST / UTC+3).
    - cron: '0 */3 * * *' 
  push: # <--- THIS IS THE CHANGE: Trigger on ANY push to the repository
    branches:
      - main # Or 'master', depending on your default branch name
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # No additional libraries are needed for this script.

    - name: Generate XML feed
      run: python generate_xml_feed.py

    - name: Commit and push XML feed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add cropink_feed.xml
        git commit -m "Automated: Generate Cropink XML feed" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
