name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl
    
    - name: Remove existing Google Chrome installation
      run: |
        sudo apt-get remove -y google-chrome-stable
    
    - name: Install Google Chrome version 114.x
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Install ChromeDriver 114.x
      run: |
        # Install ChromeDriver 114.x (compatible with Chrome 114.x)
        VERSION="114.0.5735.90"
        echo "Downloading ChromeDriver version: $VERSION"
        wget https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run tests
      run: |
        python python_test.py
        
    - name: Upload Excel file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ad-results
        path: ad_results.xlsx
