name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    
    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest
    
    - name: Get Chrome version
      run: |
        # Get the installed version of Google Chrome
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    - name: Download ChromeDriver
      run: |
        # Fetch the major version number for ChromeDriver
        CHROME_DRIVER_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
        echo "ChromeDriver major version: $CHROME_DRIVER_VERSION"
        
        # Download ChromeDriver matching the major version of Chrome
        wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}.0/chromedriver_linux64.zip

        # Unzip and move ChromeDriver to /usr/local/bin
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Run tests
      run: |
        python python_test.py
