name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    
    - name: Set up Google Chrome (Version 114)
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '114'
    
    - name: Get Chrome version
      run: |
        # Get the installed version of Google Chrome
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
        echo "Chrome version: $CHROME_VERSION"
        echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_ENV

    - name: Remove any existing ChromeDriver to avoid version conflict
      run: |
        sudo rm -f /usr/local/bin/chromedriver
    
    - name: Fetch the correct version of ChromeDriver (114.x)
      run: |
        # Use ChromeDriver for Chrome version 114.x
        VERSION="114.0.5735.90"  # Chrome version 114.x requires this driver
        echo "Downloading ChromeDriver version: $VERSION"
        wget https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
        
        # Unzip and install the correct ChromeDriver
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Run tests
      run: |
        python python_test.py
 
