name: Scrape Ads

on:
  push:
    paths:
      - 'scrape_ads.py'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Install dependencies
        run: pip install selenium

      - name: Run scraper
        run: python scrape_ads.py
