name: Scrape Prisma Market Daily

on:
  schedule:
    # Runs every three hours (00:00, 03:00, 06:00, ..., 21:00 UTC)
    # This translates to 03:00, 06:00, 09:00, ..., 00:00 EEST (UTC+3)
    - cron: '0 */3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Playwright and dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run scraping script
      run: python scrape_prisma.py

    - name: Commit and push scraped data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add prisma_products.csv
        git commit -m "Automated: Update Prisma Market products data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
