name: Scrape Prisma Market Daily

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 02:00 UTC (5 AM EEST)
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  scrape:
    runs-on: ubuntu-latest
    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions:
      contents: write # This grants write access to the repository's contents
    # ---------------------------------

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Playwright and dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run scraping script
      run: python scrape_prisma.py

    - name: Commit and push scraped data
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add prisma_products.csv
        git commit -m "Automated: Update Prisma Market products data" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
